# Generated by Django 5.1.2 on 2024-10-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kod_client', models.IntegerField(default=0)),
                ('count_tovar', models.IntegerField(default=0)),
                ('ves', models.FloatField(default=0)),
                ('trek_cod', models.CharField(max_length=32)),
            ],
        ),
    ]
